import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Mi App de NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <Navbar/>

        <main className='container mx-auto h-screen flex justify-center items-center'>
          {children}
        </main>

      </body>
    </html>
  )
}
